component_depth: 1
languages:
- php
exclude:
- /app/helpers.php
- /app/Mail/.*
- /app/Services/Forus/Notification/NotificationService.php
- /app/Exports/.*
- /app/Http/Resources/*
- /resources/.*
- /database/.*
- /routes/.*
- /config/.*
- /bootstrap/.*
- /storage/.*
- /public/.*
- .*/_ide_helper\.php
